# Generated by Django 3.2.16 on 2022-11-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date category was updated"
            ),
        ),
    ]
