# Generated by Django 3.2.16 on 2022-11-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_date_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "product category",
                "verbose_name_plural": "product categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="", max_length=200, unique=True),
        ),
    ]
