# Generated by Django 3.2.16 on 2022-11-05 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0005_auto_20221105_0859"),
        ("order", "0002_auto_20221105_1032"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_id", models.CharField(max_length=200)),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=150, null=True
                    ),
                ),
                ("brand", models.CharField(max_length=30)),
                ("exp_month", models.IntegerField()),
                ("exp_year", models.IntegerField()),
                (
                    "last4",
                    models.CharField(
                        help_text="last 4 digits of the card", max_length=4
                    ),
                ),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("Card", "Card"), ("Paypal", "Paypal")],
                        default="Card",
                        max_length=30,
                    ),
                ),
                ("amount_due", models.IntegerField(default=0)),
                ("amount_paid", models.IntegerField(default=0)),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date invoice was created"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date invoice was updated"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Payed", "Payed"),
                            ("Refunded", "Refunded"),
                            ("Failed", "Failed"),
                        ],
                        default="",
                        max_length=100,
                    ),
                ),
                (
                    "billing",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.billingaddress",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="order.order",
                    ),
                ),
            ],
        ),
    ]
