# Generated by Django 3.2.16 on 2022-11-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_inventory_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory",
            options={"ordering": ["date_created"]},
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="quantity_available",
        ),
        migrations.AddField(
            model_name="inventory",
            name="total",
            field=models.IntegerField(
                default=0, verbose_name="total quantity produced"
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="quantity_sold",
            field=models.IntegerField(default=0, verbose_name="quantity sold"),
        ),
    ]
