# Generated by Django 3.2.16 on 2022-11-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_inventory_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="quantity_sold",
            field=models.PositiveIntegerField(default=0, verbose_name="quantity sold"),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="total",
            field=models.PositiveIntegerField(
                default=0, verbose_name="total quantity produced"
            ),
        ),
    ]
