# Generated by Django 3.2.16 on 2022-11-07 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_auto_20221105_1244"),
        ("inventory", "0005_auto_20221105_1244"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to="products.product",
            ),
        ),
    ]
