# Generated by Django 3.2.16 on 2022-11-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_inventory_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="product",
        ),
    ]
