# Generated by Django 3.2.16 on 2022-11-10 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_remove_product_inventory"),
        ("inventory", "0007_remove_inventory_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="product",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to="products.product",
            ),
        ),
    ]
