# Generated by Django 3.2.16 on 2022-11-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_inventory_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="total",
            field=models.PositiveIntegerField(
                default=0, verbose_name="total quantity in stock"
            ),
        ),
    ]
