# Generated by Django 4.1.2 on 2023-05-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_inventory_total"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory",
            old_name="total",
            new_name="quantity_available",
        ),
        migrations.AddField(
            model_name="inventory",
            name="total_produced",
            field=models.PositiveIntegerField(
                default=0, verbose_name="total purchased or produced"
            ),
        ),
    ]
