# Generated by Django 3.2.16 on 2022-11-04 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_auto_20221103_1649"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promotion",
            name="coupons",
        ),
        migrations.AddField(
            model_name="promotion",
            name="coupons",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.coupons",
            ),
        ),
    ]
