# Generated by Django 3.2.16 on 2022-11-04 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_auto_20221104_0927"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotion",
            name="coupons",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.coupons",
            ),
        ),
    ]
