# Generated by Django 3.2.16 on 2022-11-04 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_date_updated"),
        ("products", "0006_alter_promotion_coupons"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="categories.subcategory",
                verbose_name="subcategory",
            ),
        ),
    ]
