# Generated by Django 3.2.16 on 2022-11-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_auto_20221104_1616"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterIndexTogether(
            name="product",
            index_together={("id", "slug")},
        ),
    ]
