# Generated by Django 3.2.16 on 2022-11-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_auto_20221105_1244"),
        ("products", "0009_auto_20221105_1244"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                related_name="product", to="categories.Category"
            ),
        ),
    ]
