# Generated by Django 3.2.16 on 2022-11-09 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.product",
            ),
        ),
    ]
