# Generated by Django 3.2.16 on 2022-11-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_media_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="image",
            field=models.ImageField(
                default="images/default.png",
                help_text="format: required, default-default.png",
                upload_to="images/",
                verbose_name="product image",
            ),
        ),
    ]
