# Generated by Django 3.2.16 on 2022-11-10 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_alter_media_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="is_feature",
            field=models.BooleanField(
                default=False,
                help_text="wether the image is the main image for that product",
                verbose_name="product default image",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="images",
                to="products.product",
            ),
        ),
    ]
