# Generated by Django 3.2.16 on 2022-11-10 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_remove_inventory_product"),
        ("products", "0013_auto_20221110_0905"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="inventory",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="inventory.inventory",
            ),
        ),
    ]
