# Generated by Django 3.2.16 on 2022-11-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_product_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=200),
        ),
    ]
