# Generated by Django 3.2.16 on 2022-11-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_remove_product_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupons",
            name="code",
            field=models.CharField(
                help_text="Coupons code (keep confidential). Must be unique.",
                max_length=50,
                unique=True,
            ),
        ),
    ]
