# Generated by Django 4.1.2 on 2022-11-16 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_rename_category_product_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="promo_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="promo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product",
                to="products.promotion",
            ),
        ),
    ]
