# Generated by Django 4.1.2 on 2022-11-17 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_product_promo_price_alter_product_promo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotion",
            name="coupons",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="promotion",
                to="products.coupons",
            ),
        ),
    ]
