# Generated by Django 4.1.2 on 2022-11-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0020_alter_promotion_coupons"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="promotion",
            name="is_schedule",
            field=models.BooleanField(default=False),
        ),
    ]
