# Generated by Django 4.1.2 on 2022-11-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_promotion_is_active_promotion_is_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="promo_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
