# Generated by Django 4.1.2 on 2023-05-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0004_alter_category_is_active"),
        ("products", "0022_alter_product_promo_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                null=True, related_name="product", to="categories.category"
            ),
        ),
    ]
