# Generated by Django 3.2.16 on 2022-11-05 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20221105_0859"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount_due",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shoppingcard",
            name="amount_due",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.shippingaddress",
            ),
        ),
    ]
