# Generated by Django 3.2.16 on 2022-11-05 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0009_auto_20221105_1244"),
        ("order", "0002_auto_20221105_1032"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date ShoppingCart was created"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date ShoppingCart was updated"
                    ),
                ),
                ("amount_due", models.IntegerField(default=0)),
                ("is_validated", models.BooleanField(default=False)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "products",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shopping Cart",
                "verbose_name_plural": "Shopping Carts",
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="shoppingcard",
        ),
        migrations.DeleteModel(
            name="ShoppingCard",
        ),
        migrations.AddField(
            model_name="order",
            name="shoppingcart",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="order.shoppingcart",
                verbose_name="Shopping Card",
            ),
        ),
    ]
