# Generated by Django 3.2.16 on 2022-11-07 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_auto_20221105_1244"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_auto_20221107_0942"),
        ("order", "0003_auto_20221105_1854"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoppingcart",
            name="is_validated",
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_address",
                to="core.shippingaddress",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shoppingcart",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="order.shoppingcart",
                verbose_name="Shopping Card",
            ),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shoppingcart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="products",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shoppingcart",
                to="products.product",
            ),
        ),
    ]
