# Generated by Django 3.2.16 on 2022-11-09 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_product_category"),
        ("order", "0006_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupons",
            field=models.OneToOneField(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="products.coupons",
            ),
        ),
    ]
