# Generated by Django 3.2.16 on 2022-11-04 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20221031_0902"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "building_number",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "street",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "city",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "postcode",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "building_number",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "street",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "city",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "postcode",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
