# Generated by Django 3.2.16 on 2022-11-05 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("core", "0004_billing_shipping"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Shipping",
            new_name="BillingAddress",
        ),
        migrations.RenameModel(
            old_name="Billing",
            new_name="ShippingAddress",
        ),
        migrations.AlterModelOptions(
            name="billingaddress",
            options={
                "verbose_name": "billing address",
                "verbose_name_plural": "billing addresses",
            },
        ),
        migrations.AlterModelOptions(
            name="shippingaddress",
            options={
                "verbose_name": "shipping address",
                "verbose_name_plural": "shipping addresses",
            },
        ),
    ]
