# Generated by Django 4.1.2 on 2022-12-12 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_auto_20221111_2027"),
    ]

    operations = [
        migrations.CreateModel(
            name="JwtToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_access", models.TextField()),
                ("token_refresh", models.TextField()),
                ("ip_address", models.CharField(blank=True, max_length=50)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("is_logged_out", models.BooleanField(default=False)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
