# Generated by Django 4.1.2 on 2023-04-16 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_jwttoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaddress",
            name="country",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="billingaddress",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 4, 16, 10, 41, 35, 330178, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="billingaddress",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="country",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 4, 16, 10, 41, 40, 465341, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
