---
name: Checks

on: [ push ]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        env:
          ENVIRONMENT: ${{secrets.ENVIRONEMENT}}
          DJANGOKEY: ${{secrets.DJANGOKEY}}
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Wait for db
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db"
      #      - name: check elestic search
      #        run: curl -X GET localhost:9200/_cluster/health
      - name: view ports
        run: docker-compose ps -a
      - name: ip address
        run: ip a
      - name: test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Checking
        run: docker-compose run --rm app sh -c "flake8"


