---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.17.7
        env:
          discovery.type: single-node
        ports:
          - 9200:9200
        environment:
            - bootstrap.memory_lock=false

        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        env:
          ENVIRONMENT: ${{secrets.ENVIRONEMENT}}
          DJANGOKEY: ${{secrets.DJANGOKEY}}
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Wait for db
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db"
      - name : test
        run : docker-compose run --rm app sh -c "python manage.py test"
      - name: Checking
        run: docker-compose run --rm app sh -c "flake8"
