---
name: Checks

on: [ push ]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    # configure elastic search on GitHub actions
#    services:
#      elasticsearch:
#        image: bitnami/elasticsearch:7.17.7
#        ports:
#          - 9200:9200

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        env:
          ENVIRONMENT: ${{secrets.ENVIRONEMENT}}
          DJANGOKEY: ${{secrets.DJANGOKEY}}
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Wait for db
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db"
      - name: view ports
        run: docker-compose ps -a
      - name: display default getway
        run: ip route | grep default
      - name: checks elasticsearch running
        run: curl -XGET http://127.0.0.1:9200/_status
      - name: test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Checking
        run: docker-compose run --rm app sh -c "flake8"


