---
name: Checks

on: [ push ]

jobs:
  test-lint:
    name: Test and Lint
    runs-on:  [self-hosted, Linux]

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        env:
          ENVIRONMENT: ${{secrets.ENVIRONEMENT}}
          DJANGOKEY: ${{secrets.DJANGOKEY}}
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d
      - name: Wait for db
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db"
      - name: test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Checking
        run: docker-compose run --rm app sh -c "flake8"
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down


